keybindings:
  back: q
  next_page: ctrl-d
  previous_page: ctrl-u
  jump_to_start: ctrl-a
  jump_to_end: ctrl-e
  jump_to_album: a
  jump_to_artist_album: A
  jump_to_context: o
  manage_devices: d
  decrease_volume: '-'
  increase_volume: +
  toggle_playback: space
  seek_backwards: <
  seek_forwards: '>'
  next_track: n
  previous_track: p
  help: '?'
  shuffle: ctrl-s
  repeat: ctrl-r
  search: /
  submit: enter
  copy_song_url: c
  copy_album_url: C
  audio_analysis: v
  basic_view: B
  add_item_to_queue: z
  open_settings: '0'
  save_settings: alt-s
behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  volume_percent: 90
  tick_rate_milliseconds: 16
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: false
  enable_global_song_count: false
  enable_discord_rpc: true
  discord_rpc_client_id: null
  shuffle_enabled: false
  liked_icon: â™¥
  shuffle_icon: ğŸ”€
  repeat_track_icon: ğŸ”‚
  repeat_context_icon: ğŸ”
  playing_icon: â–¶
  paused_icon: â¸
  set_window_title: true
  visualizer_style: Equalizer
theme:
  active: 255, 199, 153
  banner: 255, 199, 153
  error_border: 255, 128, 128
  error_text: 255, 128, 128
  hint: 255, 199, 153
  hovered: 255, 207, 168
  inactive: 190, 190, 190
  playbar_background: 22, 22, 22
  playbar_progress: 153, 255, 228
  playbar_progress_text: 255, 255, 255
  playbar_text: 210, 210, 210
  selected: 255, 199, 153
  text: 255, 255, 255
  background: 16, 16, 16
  header: 255, 255, 255
  highlighted_lyrics: 153, 255, 228
